### ISSUE TITLE
CASIA2.0 notfoundfile

### ISSUE THREAD

**Issue by dan326326** [mjkwon2021/CAT-Net#7]
Hi, I have seen the CASIA2.0 address in your code dataset_CASIA. Py, downloaded it, and set the layout and path of the dataset as required, but errors kept coming when running the code, the errors are as follows, I have also checked the path of the dataset, but they are all correct, I don't know why, could you give me some suggestions?

warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Epoch: [0/200] Iter:[0/1869], Time: 1069.73, lr: 0.005000, Loss: 0.695368
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "train.py", line 185, in main
    trainloader, optimizer, model, writer_dict, final_output_dir)
  File "E:\cat\tools\..\lib\core\function.py", line 58, in train
    for i_iter, (images, labels, qtable) in enumerate(trainloader):
  File "C:\Users\dell\anaconda3\envs\cat\lib\site-packages\torch\utils\data\dataloader.py", line 568, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\dell\anaconda3\envs\cat\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "C:\Users\dell\anaconda3\envs\cat\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\dell\anaconda3\envs\cat\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "E:\cat\tools\..\Splicing\data\data_core.py", line 99, in __getitem__
    return self.dataset_list[index//self.smallest].get_tamp(index%self.smallest)
  File "E:\cat\tools\..\Splicing\data\dataset_CASIA.py", line 55, in get_tamp
    return self._create_tensor(tamp_path, mask)
  File "E:\cat\tools\..\Splicing\data\AbstractDataset.py", line 106, in _create_tensor
    img_RGB = np.array(Image.open(im_path).convert("RGB"))
  File "C:\Users\dell\anaconda3\envs\cat\lib\site-packages\PIL\Image.py", line 2912, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\cat\\datasets\\CASIA\\CASIA 2.0\\jpg\\Tp_S_NNN_S_N_cha00089_cha00089_00871.
jpg'

**Comment by CauchyComplete** [comment]
Did you run the renaming script as described in the comment?
https://github.com/mjkwon2021/CAT-Net/blob/8e188224b9c3459c5ff60c1ef7d8e0dd2fab9353/Splicing/data/dataset_CASIA.py#L30

**Comment by dan326326** [comment]
I didn't run it, but I checked the image that reported the error, its name was correct, and it was found in the dataset

**Comment by CauchyComplete** [comment]
If only few images are causing errors, why don’t you remove that images from txt file and train without them?

**Comment by dan326326** [comment]
You're right. I have no experience in this field. Thank you for your help.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mjkwon2021/CAT-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 晚上11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mjkwon2021/CAT-Net] CASIA2.0 notfoundfile (Issue #7)





 
If only few images are causing errors, why don’t you remove that images from txt file and train without them?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
